databases:
  - name: postgres
    ipAllowList: []
services:
  - type: web
    name: rails
    # plan: free
    env: ruby
    buildCommand: “./bin/render-build.sh”
    startCommand: bundle exec rails server
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
  - type: redis
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction
# databases:
#   - name: postgres
#     ipallowlist: []
#     # databaseName: final_capstone_production
#     # user: final_capstone

# services:
#   - type: web
#     name: rails
#     env: ruby
#     buildCommand: "./bin/render-build.sh"
#     startCommand: bundle exec rails s
#     envVars:
#       - key: DATABASE_URL
#           fromDatabase:
#           name: postgres
#           property: connectionString
#       - key: RAILS_MASTER_KEY
#         sync: false
#   - type: redis
#     name: redis
#     ipallowlist: []
#     plan: free
#     maxmemoryPolicy: noeviction